exec-once = systemctl --user start hyprpolkitagent
# exec-once = mpvpaper -o "--loop-file=inf --no-audio --hwdec=auto --cache=no --panscan=1.0" ALL ~/.local/share/quickshell-lockscreen/themes_link/sword/bg.mp4

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
