---
- name: Setup Arch
  hosts: localhost
  gather_facts: true
  vars:
    tmp_dir: /tmp
    home_dir:  "{{ lookup('env', 'HOME') }}"
    dotfiles_dir: "{{ home_dir }}/dotfiles"
  tasks:
    - name: Install Packages From Main Repositories
      become: true
      community.general.pacman:
        name:
          - git
          - base-devel
          - neovim
          - stow
          - zsh
          - kitty
          - tmux
          - rust
          - go
          - zoxide
          - fzf
          - i3
          - i3blocks
          - dmenu
          - feh
          - xorg-xrandr
          - picom
          - autotiling
          - xclip
          - maim
          - docker
          - docker-compose
          - discord
          - lazygit
          - spotify-launcher
          - appimagelauncher
          - ttf-jetbrains-mono-nerd
          - ttf-meslo-nerd
        state: latest
        update_cache: true

    - name: Check if YAY does exist
      command: which yay
      changed_when: false
      failed_when: which_res.rc > 1
      register: which_res
      
    - name: Clone the YAY repo
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: "{{ tmp_dir }}/yay"
      when: which_res.rc != 0

    - name: Install YAY
      ansible.builtin.command:
      args:
        chdir: "{{ tmp_dir }}/yay"
        cmd: makepkg -si --noconfirm
      when: which_res.rc != 0
        
    - name: Install Packages From AUR
      command: yay -Sy --noconfirm {{ item }}
      with_items:
        - brave
        - vscodium
        - bun
        - fnm
        - lazydocker

    - name: Get ZSH Path
      command: which zsh
      register: zsh_path

    - name: Set Default Shell
      become: true
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: "{{ zsh_path.stdout }}"
        groups: docker
        append: yes
        
    - name: Clone My Dotfiles repo
      ansible.builtin.git:
        repo: 'https://github.com/IssaMDOunejjaR/dotfiles'
        dest: "{{ dotfiles_dir }}"
        force: true
        
    - name: Clone Tmux Plugin Manager Repo
      ansible.builtin.git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: "{{ home_dir }}/.tmux/plugins/tpm"
        force: true

    - name: Copy Tmux Sessionizer to /usr/bin
      become: true
      ansible.builtin.copy:
        src: "{{ dotfiles_dir }}/srcs/tmux-sessionizer"
        dest: /usr/local/bin/tmux-sessionizer
        mode: '0755'
        
    - name: Start And Enable Service Docker
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ home_dir }}/Documents/Projects"
        - "{{ home_dir }}/Documents/Learning"

    - name: Symlink My Config Files Using Stow
      ansible.builtin.command:
      args:
        chdir: "{{ dotfiles_dir }}"
        cmd: stow --adopt .
