---
- name: Setup Ubuntu
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update and Upgrade APT Cache
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Install Packages From Main Repositories
      become: true
      apt:
        name:
          - git
          - curl
          - vim
          - unzip
          - fontconfig
          - build-essential
          - python3.12-venv
          - maim
          - pulseaudio
          - stow
          - zsh
          - kitty
          - tmux
          - rustc
          - golang
          - zoxide
          - fzf
          - i3
          - i3blocks
          - dmenu
          - autotiling
          - feh
          - x11-xserver-utils
          - picom
          - docker.io
          - docker-compose
          - fonts-jetbrains-mono
          - fonts-hack-ttf
        state: latest

    - name: Install Additional Tools via Snap
      become: true
      snap:
        name: "{{ item }}"
        state: present
        classic: true
      loop:
        - brave
        - codium
        - discord
        - spotify
        - nvim

    - name: Run Homebrew installation script
      ansible.builtin.shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Eval Homebrew
      ansible.builtin.shell:
        cmd: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        
    - name: Install Additional Tools via Brew
      community.general.homebrew:
        name:
          - lazygit
          - lazydocker
          - bun
          - fnm
        state: latest
        update_homebrew: true
          
    - name: Download JetBrainsMono Nerd Font
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
        dest: /tmp/JetBrainsMono.zip
        mode: '0644'
        
    - name: Download Meslo Nerd Font
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.zip"
        dest: /tmp/Meslo.zip
        mode: '0644'

    - name: Create fonts directory
      ansible.builtin.file:
        path: "{{ home_dir }}/.fonts"
        state: directory
        mode: '0755'

    - name: Unzip JetBrainsMono Nerd Font to ~/.fonts
      ansible.builtin.unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: "{{ home_dir }}/.fonts"
        remote_src: yes
        
    - name: Unzip Meslo Nerd Font to ~/.fonts
      ansible.builtin.unarchive:
        src: /tmp/Meslo.zip
        dest: "{{ home_dir }}/.fonts"
        remote_src: yes

    - name: Rebuild font cache
      ansible.builtin.command:
        cmd: fc-cache -fv
