---
- name: Setup Ubuntu
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update and Upgrade APT Cache
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Install Packages From Main Repositories
      become: true
      apt:
        name:
          - git
          - curl
          - vim
          - build-essential
          - python3.12-venv
          - stow
          - zsh
          - kitty
          - tmux
          - rustc
          - golang
          - zoxide
          - fzf
          - i3
          - i3blocks
          - dmenu
          - feh
          - x11-xserver-utils
          - picom
          - docker.io
          - docker-compose
          - fonts-jetbrains-mono
          - fonts-hack-ttf
        state: latest

    - name: Install Additional Tools via Snap
      become: true
      snap:
        name: "{{ item }}"
        state: present
        classic: true
      loop:
        - brave
        - codium
        - discord
        - spotify
        - nvim

    - name: Run Homebrew installation script
      ansible.builtin.shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install Additional Tools via Brew
      community.general.homebrew:
        name:
          - lazygit
          - lazydocker
          - oven-sh/bun/bun
