#!/bin/bash

if [[ -z ${COMMAND_ON} || -z ${COMMAND_OFF} || -z ${COMMAND_STATUS} ]]; then
  echo "All of COMMAND_ON, COMMAND_OFF, and COMMAND_STATUS are required" >&2
  exit 1
fi

on_cmd=${COMMAND_ON}
off_cmd=${COMMAND_OFF}
status_cmd=${COMMAND_STATUS}
open_cmd=${COMMAND_OPEN}

if (( ${BLOCK_BUTTON:-0} == 1 )); then
  # eval $status_cmd 2>&1 >/dev/null
  
  if $status_cmd 2>&1 >/dev/null; then
    echo "OFF" >> /home/issamdounejjar/.config/i3blocks/out.log
    $off_cmd 2>&1 >/dev/null
  else
    echo "ON" >> /home/issamdounejjar/.config/i3blocks/out.log
    $on_cmd 2>&1 >>/home/issamdounejjar/.config/i3blocks/out.log
  fi
fi

if [[ -n ${COMMAND_OPEN} && ${BLOCK_BUTTON:-0} -eq 3 ]]; then
  eval "$open_cmd" >/dev/null 2>&1 &
fi

eval $status_cmd 2>&1 >/dev/null
if (( $? == 0 )); then
  COLOR=${COLOR_ON}
else
  COLOR=${COLOR_OFF:-#555555}
fi

echo
echo
echo $COLOR
