#!/bin/bash

CMD=$(printf "suspend\nreboot\nshutdown" | wofi --dmenu --prompt "Select action")

case "$CMD" in
  suspend)
    systemctl suspend
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
esac
