#!/bin/bash

CMD=$(printf "logout\nsuspend\nreboot\nshutdown" | rofi -dmenu -no-show-icons --prompt "Select action")

case "$CMD" in
logout)
  i3-msg exit
  ;;
suspend)
  systemctl suspend
  ;;
reboot)
  systemctl reboot
  ;;
shutdown)
  systemctl poweroff
  ;;
esac
