require("configs.lazy")
require("configs.lsp-zero")
require("configs.treesitter")
require("configs.indent-blankline")
require("configs.telescope")
require("configs.harpoon")
require("configs.rust-tools")
