#!/bin/bash

CMD=$(printf "suspend\nreboot\nshutdown" | rofi -dmenu -no-show-icons --prompt "Select action")

case "$CMD" in
  suspend)
    systemctl suspend
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
esac
