[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[window]
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12
