require("plugins.configs.lazy")
require("plugins.configs.treesitter")
require("plugins.configs.lsp-zero")
require("plugins.configs.telescope")
require("plugins.configs.comment")
require("plugins.configs.colorizer")
